brace_style = "AlwaysNextLine"
comment_width = 140
control_brace_style = "AlwaysNextLine"
fn_params_layout = "Compressed"
fn_single_line = true
max_width = 140
imports_granularity = "Item"
normalize_doc_attributes = true
group_imports = "StdExternalCrate"